services:
  rabbitmq:
    image: rabbitmq:4.0.8-management
    hostname: rabbit-mq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430-5432:5432"
    deploy:
      replicas: 2
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_admin -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
