services:

  config-server:
    build:
      context: .
      dockerfile: dockerfiles/ConfigServer/Dockerfile
    ports:
      - "8888:8888"
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  eureka-server:
    build:
      context: .
      dockerfile: dockerfiles/EurekaServer/Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  api-gateway:
    build:
      context: .
      dockerfile: dockerfiles/ApiGateway/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - app-network


  brt-service:
    build:
      context: .
      dockerfile: dockerfiles/BRTService/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8090-9000:8081"
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      config-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      brt-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      hrs-service:
        condition: service_healthy
    networks:
      - app-network


  cdr-service:
    build:
      context: .
      dockerfile: dockerfiles/CDRService/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8082:8082"
    depends_on:
      config-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - app-network

  hrs-service:
    build:
      context: .
      dockerfile: dockerfiles/HRSService/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8070-8079:8084"
    healthcheck:
      test: "curl --fail --silent localhost:8084/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      hrs-db:
        condition: service_healthy
    networks:
      - app-network

  crm-service:
    build:
      context: .
      dockerfile: dockerfiles/CRMService/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8060-8069:8083"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      brt-service:
        condition: service_healthy

    networks:
      - app-network

  sso-service:
    build:
      context: .
      dockerfile: dockerfiles/SSOService/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8765:8765"
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - app-network


  rabbitmq:
    image: rabbitmq:4.0.8-management
    hostname: rabbit-mq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  brt-db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brt-db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  hrs-db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hrs-db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  sso-db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sso-db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge